package model;

import model.code.codeNV;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;

public class nhanvien extends javax.swing.JFrame {
    private List <codeNV> list = new ArrayList<>();
    private DefaultTableModel tblModel = new DefaultTableModel();

    public nhanvien() {
        initComponents();
        
        initTable();
        fillTable();
    }
    
    private void fillTable(){
        tblModel.setRowCount(0);
        
        
        for (codeNV nhanvien : list){
            tblModel.addRow(new String[]{nhanvien.getmaNV(), nhanvien.gettenNV(),nhanvien.getdiachiNV(), nhanvien.getvitri()}
            );
        }
        tblModel.fireTableDataChanged();
    }
    
    private void initTable(){
        String[] columns = new String[] {"Mã nhân viên", "Họ tên nhân viên", "Địa chỉ", "Vị trí"};
                
        tblModel.setColumnIdentifiers(columns);
        
        list.add(new codeNV("NV1","Tran Viet Hoang","Ha Noi","Quan ly"));
        list.add(new codeNV("NV2","Mai Ngoc Quyen","Hai Phong","Quan ly"));
        list.add(new codeNV("NV3","Do Duc Quoc Chien","Ha Noi","Quan ly"));
        list.add(new codeNV("NV4","Nguyen Tai Thu","Ha Noi","Quan ly"));
        list.add(new codeNV("NV5","Pham Duc Trung","Nha Trang","Nhan vien"));
        
        bangNV.setModel(tblModel);
    }
    
    @SuppressWarnings("unchecked")

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtmaNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tenNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        diachiNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        vitri = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bangNV = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Quản lý nhân viên");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Illustration.png"))); // NOI18N
        jButton3.setText("Quay lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, -1, -1));

        txtmaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaNVActionPerformed(evt);
            }
        });
        jPanel1.add(txtmaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 6, 307, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Họ tên nhân viên:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 46, -1, -1));
        jPanel1.add(tenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 46, 307, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Địa chỉ:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 86, -1, -1));
        jPanel1.add(diachiNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 86, 307, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Vị trí:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 126, -1, -1));
        jPanel1.add(vitri, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 126, 307, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 815, 10));

        add.setText("Thêm");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 176, -1, -1));

        edit.setText("Cập nhật");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 176, -1, -1));

        delete.setText("Xóa");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 176, -1, -1));

        bangNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bangNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangNVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bangNV);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 211, 930, -1));

        jButton1.setText("Nhập mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 176, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/123456.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -210, 940, 920));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 930, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 819, 10));

        jLabel6.setBackground(new java.awt.Color(153, 153, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo-tongcuc.png"))); // NOI18N
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 106));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/123456.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 940, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaNVActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        StringBuilder sb = new StringBuilder();
        if (txtmaNV.getText().equals("")){
            sb.append("Mã nhân viên không được để trống \n");
        }
        if (tenNV.getText().equals("")){
            sb.append("Tên nhân viên không được để trống \n");
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        codeNV nhanvien = new codeNV();
        nhanvien.setmaNV(txtmaNV.getText());
        nhanvien.settenNV(tenNV.getText());
        nhanvien.setdiachiNV(diachiNV.getText());
        nhanvien.setvitri(vitri.getText());
        
        list.add(nhanvien);
        
        fillTable();
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        StringBuilder sb = new StringBuilder();
        if (txtmaNV.getText().equals("")){
            sb.append("Mã sinh viên không được để trống \n");
        }
        
        if (sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa ko?", "Hỏi", 
                JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION){
            return;
        }
        
        for (codeNV nhanvien : list) {
            if (nhanvien.getmaNV().equals(txtmaNV.getText())){
                list.remove(nhanvien);
                
                break;
            }
        }
        fillTable();    
    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        StringBuilder sb = new StringBuilder();
        if (txtmaNV.getText().equals("")){
            sb.append("Mã nhân viên không được để trống \n");
        }
        if (tenNV.getText().equals("")){
            sb.append("Họ tên nhân viên không được để trống \n");
        }
        if (sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        

        
        for (codeNV nhanvien : list) {
            if (nhanvien.getmaNV().equals(txtmaNV.getText())){
                nhanvien.settenNV(tenNV.getText());
                nhanvien.setdiachiNV(diachiNV.getText());
                nhanvien.setvitri(vitri.getText());
                
                break;
            }
        }
        fillTable(); 
        
    }//GEN-LAST:event_editActionPerformed

    private void bangNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangNVMouseClicked
        int selectedRow = bangNV.getSelectedRow();
        
        if(selectedRow>=0) {
            String maNV = (String) bangNV.getValueAt(selectedRow, 0);
            
            for (codeNV nhanvien : list) {
                if (maNV.equals(nhanvien.getmaNV())){
                    txtmaNV.setText(maNV);
                    tenNV.setText(nhanvien.gettenNV());
                    diachiNV.setText(nhanvien.getdiachiNV());
                    vitri.setText(nhanvien.getvitri());

                    break;
                }
            }
        }
    }//GEN-LAST:event_bangNVMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtmaNV.setText("");
        tenNV.setText("");
        diachiNV.setText("");
        vitri.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nhanvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTable bangNV;
    private javax.swing.JButton delete;
    private javax.swing.JTextField diachiNV;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField tenNV;
    private javax.swing.JTextField txtmaNV;
    private javax.swing.JTextField vitri;
    // End of variables declaration//GEN-END:variables

}
